version: 2
jobs:
  build:
    machine:
      enabled: true
      docker_layer_caching: true
    steps:
    - checkout
    - run: "export CODECOV_CI_ENV=$(curl -s https://codecov.io/env | bash | sed -e 's/-e /--build-arg /g')"
    - run: "docker login -u $DOCKER_USER -p $DOCKER_PASS"
    - run: "docker build --build-arg $CODECOV_CI_ENV -t queer/singyeong:$(echo $CIRCLE_BRANCH | sed -e 's|/|_|g')-$CIRCLE_BUILD_NUM ."
  build-and-push:
    machine:
      enabled: true
      docker_layer_caching: true
    steps:
    - checkout
    - run: "export CODECOV_CI_ENV=$(curl -s https://codecov.io/env | bash | sed -e 's/-e /--build-arg /g')"
    - run: "docker login -u $DOCKER_USER -p $DOCKER_PASS"
    - run: "docker build --build-arg $CODECOV_CI_ENV -t queer/singyeong:$(echo $CIRCLE_BRANCH | sed -e 's|/|_|g')-$CIRCLE_BUILD_NUM ."
    - run: "docker push queer/singyeong:$(echo $CIRCLE_BRANCH | sed -e 's|/|_|g')-$CIRCLE_BUILD_NUM"

workflows:
  version: 2
  build:
    jobs:
    - build:
        filters:
          branches:
            ignore:
            - master
  build-and-push:
    jobs:
    - build-and-push:
        filters:
          branches:
            only:
            - master